db/urls.py
from django.conf.urls import patterns, url

from db import views
from views import product, checkpaypal, Basket, transactionSummary, page

urlpatterns = patterns('',
    url(r'^$', page.home, name='home'),

    url(r'^product.json', product.getJson, name='jsonProduct'),
    url(r'^productdef.json', product.getDefaultJson, name='jsonDefaultProduct'),
    url(r'^product/Basket.json', Basket.getJson, name='jsonBasket'),
    url(r'^product$', product.index, name='indexProduct'),
    url(r'^product/new$', product.new, name='newProduct'),
    url(r'^product/create$', product.create, name='createProduct'),
    url(r'^product/(?P<prod_barcode>\w+)/edit$', product.edit, name='editProduct'),
    url(r'^product/(?P<prod_barcode>\w+)/update$', product.update, name='updateProduct'),
    url(r'^product/(?P<prod_barcode>\w+)/destroy$', product.destroy, name='destroyProduct'),
    url(r'^product/AddToBasket$', Basket.AddToBasket, name='AddToBasket'),
    url(r'^product/ClearBasket$', Basket.clearBasket, name='clearBasket'),

    url(r'^Basket$', Basket.index, name='Basket'),
    url(r'^Basket.json', Basket.getJson, name='jsonBasket'),

    url(r'^DefaultBasket$', product.defindex, name='DefaultBasket'),

    url(r'^product/(?P<prod_barcode>\w+)$', product.show, name='showProduct'),
    url(r'^product/get/(?P<prod_barcode>\w+)$', product.get, name='getProduct'),
    
    url(r'^transactionSummary.json', transactionSummary.getJson, name='jsonTransactionSummary'),
    url(r'^trans$', transactionSummary.ExpressCheckout, name='testSale'),
    url(r'^transactionSummary/CompleteOrder$',transactionSummary.CompleteOrder, name='CompleteOrder'),
    url(r'^transactionSummary/success$',transactionSummary.success, name='success'),
    url(r'^transactionSummary/failure$',transactionSummary.failure, name='failure'),

    url(r'^defaulttrans$', transactionSummary.defaultExpressCheckout, name='defaultSale'),
    url(r'^transactionSummary/defaultCompleteOrder$',transactionSummary.defaultCompleteOrder, name='defaultCompleteOrder'),
    url(r'^transactionSummary/defaultsuccess$',transactionSummary.defaultSuccess, name='defaultsuccess'),
    url(r'^transactionSummary/defaultfailure$',transactionSummary.defaultFailure, name='defaultfailure'),
)

hq_local/urls.py
from django.conf.urls import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^', include('db.urls', namespace="db")),
    #url(r'^checkout/', include('paypal_express_checkout.urls')),
    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/$', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/$', include(admin.site.urls)),
)

db/views/Basket.py
from django.core import serializers
from django.core.paginator import Paginator, EmptyPage
from django.core.urlresolvers import reverse
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.contrib import messages
from django.utils.datastructures import SortedDict
import json
from json import dumps, loads, JSONEncoder, JSONDecoder
import pickle
from db.models import Product
import unittest
import warnings
import unittest
import warnings

import urllib, md5, datetime
from cgi import parse_qs
#overide default json encoder to support non-primitive data-types
class PythonObjectEncoder(JSONEncoder):
    def default(self, obj):
        if isinstance(obj, (list, dict, str, unicode, int, float, bool, type(None))):
            return JSONEncoder.default(self, obj)
        return {'_python_object': pickle.dumps(obj)}

def as_python_object(dct):
    if '_python_object' in dct:
        return pickle.loads(str(dct['_python_object']))
    return dct

#declare products to be added to basket. It cosists of quantity of each product as well
class ProductforBasket:
    barcode = ''
    name = ''
    category = ''
    manufacturer = ''
    cost_price = None 
    quantity = None
    def __init__(self, prod_barcode, quantity, name, category, manufacturer, cost_price):
        self.barcode = prod_barcode
        self.quantity = quantity
        self.name  = name
        self.category = category
        self.manufacturer =  manufacturer
        self.cost_price = cost_price

    def as_json(self):
        # we use sorted dict to preserve order in which key/value pair is inserted
        # this is so that it won't mess up the json when we try to render it client-side
        dict = SortedDict()
        dict['barcode'] =  self.barcode
        dict['name'] = self.name
        dict['category'] = self.category
        dict['manufacturer'] = self.manufacturer
        dict['cost_price'] = "%0.2f" % self.cost_price
        dict['quantity'] = self.quantity
        return dict

#declare shopping basket for every new user using sessions
class Basket:
    productList = None
    def __init__(self):
        self.productList = []

    # API METHODS
    def AddToBasket(self, prod_barcode, quantity, name, category, manufacturer, cost_price):
        P = ProductforBasket(prod_barcode, quantity, name, category, manufacturer, cost_price)
        self.productList.append(P)
        
    def getProductList(self):
         return self.productList

    def RemoveFromBasket(self, prod_barcode):
        for i in productList:
            if( i.barcode == prod_barcode):
                productList.remove(i)

# HTTP verb: GET
# Path: /Basket
# Used for: display the user's active basker
def index(request):
    data = {}
    total = '0.0'
    try:
        total = request.session['total']
    except:
        request.session['total'] = '0.0'
        total = 0.0
    try:
        data = request.session['list']
    except:
        total = request.session['total']
    request.session['list'] = data
    request.session['total'] = total
    return render(request, 'product/AddToBasket.html', {'total': total})

#function called on adding products to basket. Adds the session variable as well.
def AddToBasket(request):
    B = Basket()
    product_l = []
    previous = []
    prevT = '0.0'
    try:
        previous = request.session['list']
    except:
        request.session['list'] = ''
    try:
        prevT = request.session['total']
    except:
        request.session['total'] = '0.0'
    total = 0
    request.session.flush()
    product_list = Product.objects.all().filter(is_valid=True)
    for product in product_list:
        temp = str(product.barcode)
        quant = temp+'Q'
        if temp in request.POST:
            quantity = request.POST[quant]
            B.AddToBasket(product.barcode, quantity, product.name, product.category, product.manufacturer, product.cost_price) 
    productList = B.getProductList()
    if productList is not None:
        for product in productList:
            total += product.cost_price * int(product.quantity)
    response_data = {}
    response_data["rows"] = [ob.as_json() for ob in productList]
    request.session['list'] = ''
    if request.session['list'] is not None:
        for product_list in previous:
            dict = SortedDict()
            dict['barcode'] =  product_list['barcode']
            dict['name'] = product_list['name']
            dict['category'] = product_list['category']
            dict['manufacturer'] =product_list['manufacturer']
            dict['cost_price'] = product_list['cost_price']
            dict['quantity'] = product_list['quantity']
            product_l.append(dict)
        for ob in productList:
            dict = ob.as_json()
            product_l.append(dict)
        nowT = float(prevT) + float(total)
        request.session['list'] = product_l
        request.session['total'] = str(nowT)
    else:
        request.session['list'] = response_data["rows"]
        request.session['total'] = str(total)
    total = request.session['total']
    return render(request, 'product/AddToBasket.html', {'total': total, 'data' : response_data})

# HTTP verb: GET
# Path: /clearBasket
# Used for: clear the contents of the basket
def clearBasket(request):
    request.session.flush()
    request.session['list'] = ''
    request.session['total'] = '0.0'
    total = request.session['total']
    return render(request, 'product/AddToBasket.html', {'total': total})

# HTTP verb: GET
# Path: along the line of /Basket.json?page=0&filter[1]=abc&column[2]=0
# Used in AJAX call from tablesorter jquery plugin from index page to sort/filter/go to next page
# return JSON data
def getJson(request):
    # url in form of : http://localhost:8000/product.json?page=0&filter[1]=a&filter[2]=b&column[8]=0
    # go through each get request variable
    product_l = []
    product = request.session['list']
    for product_list in product:
        dict = SortedDict()
        dict['barcode'] =  product_list['barcode']
        dict['name'] = product_list['name']
        dict['category'] = product_list['category']
        dict['manufacturer'] =product_list['manufacturer']
        dict['cost_price'] = product_list['cost_price']
        dict['quantity'] =product_list['quantity']
        product_l.append(dict)

    for key in request.GET: 
        if key == "filter[0]":
            product_list = product_list.filter(barcode__icontains=request.GET.get(key))
        if key == "filter[1]":
            product_list = product_list.filter(name__icontains=request.GET.get(key))
        if key == "filter[2]":
            product_list = product_list.filter(category__icontains=request.GET.get(key))
        if key == "filter[3]":
            product_list = product_list.filter(manufacturer__icontains=request.GET.get(key))
        if key == "filter[4]":
            product_list = product_list.filter(cost_price__icontains=request.GET.get(key))
        if key == "filter[5]":
            product_list = product_list.filter(quantity__icontains=request.GET.get(key))
    
    for key in request.GET:
        value = request.GET.get(key)
        if key == "column[0]":
            product_list = product_list.order_by("barcode") if value == "0" else product_list.order_by("-barcode")
        if key == "column[1]":
            product_list = product_list.order_by("name") if value == "0" else product_list.order_by("-name")
        if key == "column[2]":
            product_list = product_list.order_by("category") if value == "0" else product_list.order_by("-category")
        if key == "column[3]":
            product_list = product_list.order_by("manufacturer") if value == "0" else product_list.order_by("-manufacturer")
        if key == "column[4]":
            product_list = product_list.order_by("cost_price") if value == "0" else product_list.order_by("-cost_price")
        if key == "column[5]":
            product_list = product_list.order_by("quantity") if value == "0" else product_list.order_by("-quantity")

    paginator = Paginator(product_l, 100) #100 entries at a time
    page = request.GET.get('page') 

    try:
        product_on_page = paginator.page(int(page or 0) + 1) # if page is None, just use 0 ( and + 1 because it's zero-based on client side)
    except EmptyPage:
        product_on_page = paginator.page(paginator.num_pages)

    response_data = {}
    if len(product_l) is not None:
        length = len(product_l)
    else:
        length = 0;
    response_data["total_rows"] = length
    response_data["headers"] = ["Barcode", "Name", "Category", "Manufacturer", "Cost Price", "Quantity"]
    # serializers.serialize("json", array of obj) won't give us a json in a structure that we want.
    response_data["rows"] = product_l
    # print response_data
    return HttpResponse(json.dumps(response_data), content_type="application/json")

db/views/Testpaypal.py
from django.core import serializers
from django.core.paginator import Paginator, EmptyPage
from django.core.urlresolvers import reverse
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.contrib import messages
import json
from hq_local.settings import USER, PWD, SIGNATURE, VERSION
from db.models import Product
import unittest
import warnings
import unittest
import warnings

import urllib, md5, datetime
from cgi import parse_qs

# This class is desgined to call the Paypal API. Not used any PayPal packages to achieve this. 
# PWD, SIGNATURE  and USER is stored safely in the setting.py file to prevent access to everyone other than the admin and root
# Implemented on Sandvox enviroment. Self- declared all API functions for PayPal from the online documentation available.
# There is no direct support available for python and ExpressCheckout

class PayPal:
    """ #PayPal utility class"""
    signature_values = {}
    API_ENDPOINT = ""
    PAYPAL_URL = ""
    
    def __init__(self):
        ## Sandbox values
        self.signature_values = {
        'USER' : USER, # Edit this to your API user name
        'PWD' : PWD, # Edit this to your API password
        'SIGNATURE' : SIGNATURE, # edit this to your API signature
        'VERSION' : VERSION,
        }
        self.API_ENDPOINT = 'https://api-3t.sandbox.paypal.com/nvp' # Sandbox URL, not production
        self.PAYPAL_URL = 'https://www.sandbox.paypal.com/webscr&cmd=_express-checkout&token='
        self.signature = urllib.urlencode(self.signature_values) + "&"

    # API METHODS
    def SetExpressCheckout(self, return_url, cancel_url, product_list, **kwargs):
        params = {
            'METHOD' : "SetExpressCheckout",
            'NOSHIPPING' : 1,
            'PAYMENTACTION' : 'Sale',
            'RETURNURL' : return_url,
            'CANCELURL' : cancel_url,
            'ALLOWNOTE' :1,
            'PAYMENTREQUEST_0_PAYMENTACTION':'Sale',
            'PAYMENTREQUEST_0_CURRENCYCODE':'USD',
            'PAGESTYLE' : 'CentreOne',
        }
        m = 0;
        total = 0;
        for i in product_list:
            key = 'L_PAYMENTREQUEST_0_NAME' + str(m)
            params[key] = i['name']
            key = 'L_PAYMENTREQUEST_0_QTY' + str(m)
            params[key] = i['quantity']
            key = 'L_PAYMENTREQUEST_0_AMT' +str(m)
            params[key] = i['cost_price']
            total += (float(i['cost_price']) * int(i['quantity'])) #change by quantity
            key = 'L_PAYMENTREQUEST_0_DESC' + str(m)
            params[key] = i['manufacturer']
            key = 'L_PAYMENTREQUEST_0_NUMBER' + str(m)
            params[key] = i['barcode']
            m = m + 1
        params['PAYMENTREQUEST_0_AMT'] = total
        params.update(kwargs)
        params_string = self.signature + urllib.urlencode(params)
        response = urllib.urlopen(self.API_ENDPOINT, params_string).read()
        response_dict = parse_qs(response)
        response_token = response_dict['TOKEN'][0]
        return response_token
    
    def GetExpressCheckoutDetails(self, token, return_all = False):
        params = {
            'METHOD' : "GetExpressCheckoutDetails",
            'TOKEN' : token,
        }
        params_string = self.signature + urllib.urlencode(params)
        response = urllib.urlopen(self.API_ENDPOINT, params_string).read()
        response_dict = parse_qs(response)
        if return_all:
            return response_dict
        try:
            response_token = response_dict['TOKEN'][0]
        except KeyError:
            response_token = response_dict
        return response_token
    
    def DoExpressCheckoutPayment(self, token, payer_id, amt):
        params = {
            'METHOD' : "DoExpressCheckoutPayment",
            'TOKEN' : token,
            'AMT' : amt,
            'PAYERID' : payer_id,
            'PAYMENTACTION' : 'Sale',
        }
        params_string = self.signature + urllib.urlencode(params)
        response = urllib.urlopen(self.API_ENDPOINT, params_string).read()
        response_tokens = {}
        for token in response.split('&'):
            response_tokens[token.split("=")[0]] = token.split("=")[1]
        for key in response_tokens.keys():
                response_tokens[key] = urllib.unquote(response_tokens[key])
        print response_tokens
        return response_tokens
        
    def GetTransactionDetails(self, tx_id):
        params = {
            'METHOD' : "GetTransactionDetails", 
            'TRANSACTIONID' : tx_id,
        }
        params_string = self.signature + urllib.urlencode(params)
        response = urllib.urlopen(self.API_ENDPOINT, params_string).read()
        response_tokens = {}
        for token in response.split('&'):
            response_tokens[token.split("=")[0]] = token.split("=")[1]
        for key in response_tokens.keys():
                response_tokens[key] = urllib.unquote(response_tokens[key])
        return response_tokens    

db/views/checkpaypal.py
from django.core import serializers
from django.core.paginator import Paginator, EmptyPage
from django.core.urlresolvers import reverse
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.contrib import messages
import json

from db.models import Product
from db.views import Testpaypal
import unittest
import warnings
#import paypal
import unittest
import warnings

from Testpaypal import *
#testing paypal - not used anymore
p = PayPal()
def ExpressCheckout(barcode):
	token = p.SetExpressCheckout('120', 'http://www.yoursite.com/returnurl', 'http://www.yoursite.com/cancelurl');
	s ='https://www.sandbox.paypal.com/webscr&cmd=_express-checkout&token=' + token;

db/views/page.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.core.urlresolvers import reverse
from django.http import Http404
from hq_local.settings import *

def home(request):
    return render(request, 'home.html')
    
def management(request):
    return render(request, 'management.html')

db/templates/home.html
{% extends "layout.html" %}
{% load staticfiles %}

{% block css %}
    <link href="{% static "css/custom.css" %}" rel="stylesheet" media="screen">
{% endblock %}

{% block javascript %}
<script>
    $(window).load(function() {    

      var theWindow        = $(window),
          $bg              = $("#bg"),
          aspectRatio      = $bg.width() / $bg.height();
                        
      function resizeBg() {
        
        if ( (theWindow.width() / theWindow.height()) < aspectRatio ) {
            $bg
              .removeClass()
              .addClass('bgheight');
        } else {
            $bg
              .removeClass()
              .addClass('bgwidth');
        }
              
      }
                              
      theWindow.resize(resizeBg).trigger("resize");

      
    });
    
        $(function(){
                // Setup drop down menu
                  $('.dropdown-toggle').dropdown();
                 
                  // Fix input element click problem
                  $('.dropdown input, .dropdown label').click(function(e) {
                    e.stopPropagation();
                  });
                });
    </script>
{% endblock %}

{% block afterbody %}
<img src="{% static "img/bg.jpg" %}" id="bg" alt="">
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-md-12">
    <h1>Welcome!</h1>
    <br />
  </div>
</div>

<div class="row">
  <div class="col-md-3">
    <div class="item-unit">
      <a href="{% url 'db:indexProduct' %}">
        <div class="item-unit-content">
          <img src = "{% static "img/product.svg" %}"/>
          <br />
          <h2>Product</h2>
        </div>
      </a>
    </div>
  </div>
  <div class="col-md-3">
    <div class="item-unit">
      <a href="{% url 'db:Basket' %}">
        <div class="item-unit-content">
          <img src = "{% static "img/transaction.svg" %}"/>
          <h2>Active Basket</h2>
        </div>
      </a>
    </div>
  </div>
    <div class="col-md-3">
    <div class="item-unit">
      <a href="{% url 'db:DefaultBasket' %}">
        <div class="item-unit-content">
          <img src = "{% static "img/transaction.svg" %}"/>
          <h2>Default Basket</h2>
        </div>
      </a>
    </div>
  </div>

</div>
{% endblock %}

db/templates/layout.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %}Centre One{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet" media="screen">
    <link rel="shortcut icon" href="{% static "img/favicon.ico" %}" type="image/x-icon">
    {% block css %}{% endblock %}
    

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="../../assets/js/html5shiv.js"></script>
      <script src="../../assets/js/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    {% block afterbody %}{% endblock %}
    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-nav" href="{% url 'db:home' %}"><img  src = "{% static "img/logo.png" %}" href="{% url 'db:home' %}" type=img></a-->
          
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a class="navbar-nav" href="{% url 'db:indexProduct' %}">Product</a></li>
            <li><a href="{% url 'db:Basket' %}">Active Basket</a></li>
            <li><a href="{% url 'db:DefaultBasket' %}">Default Basket</a></li>
            
            <!--li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
            -->
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
    
    <!-- start of content.-->
    <div class="container">


    {% if messages %}
        {% for message in messages %}
          {% if message.tags == "error" %}
            <div class="alert alert-danger">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <strong>{{ message.tags }}</strong> {{ message }}
            </div>
          {% elif  message.tags == "success" %}
            <div class="alert alert-success">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <strong>{{ message.tags }}</strong> {{ message }}
            </div>
          {% else %}
            <div class="alert alert-info">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <strong>{{ message.tags }}</strong> {{ message }}
            </div>
          {% endif %}
        {% endfor %}
    {% endif %}

      
      
    {% block content %}
      <h1>Hello, world!</h1>
    {% endblock %}
    </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="{% static "js/jquery.js" %}"></script>
    <script src="{% static "constant.js" %}"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    
    {% block javascript %}{% endblock %}
    {% block gmap %}{% endblock %}
  </body>
</html>