db/urls.py
from django.conf.urls import patterns, url

from db import views
from views import product, checkpaypal, Basket, transactionSummary, page

urlpatterns = patterns('',
    url(r'^$', page.home, name='home'),

    url(r'^product.json', product.getJson, name='jsonProduct'),
    url(r'^productdef.json', product.getDefaultJson, name='jsonDefaultProduct'),
    url(r'^product/Basket.json', Basket.getJson, name='jsonBasket'),
    url(r'^product$', product.index, name='indexProduct'),
    url(r'^product/new$', product.new, name='newProduct'),
    url(r'^product/create$', product.create, name='createProduct'),
    url(r'^product/(?P<prod_barcode>\w+)/edit$', product.edit, name='editProduct'),
    url(r'^product/(?P<prod_barcode>\w+)/update$', product.update, name='updateProduct'),
    url(r'^product/(?P<prod_barcode>\w+)/destroy$', product.destroy, name='destroyProduct'),
    url(r'^product/AddToBasket$', Basket.AddToBasket, name='AddToBasket'),
    url(r'^product/ClearBasket$', Basket.clearBasket, name='clearBasket'),

    url(r'^Basket$', Basket.index, name='Basket'),
    url(r'^Basket.json', Basket.getJson, name='jsonBasket'),

    url(r'^DefaultBasket$', product.defindex, name='DefaultBasket'),

    url(r'^product/(?P<prod_barcode>\w+)$', product.show, name='showProduct'),
    url(r'^product/get/(?P<prod_barcode>\w+)$', product.get, name='getProduct'),
    
    url(r'^transactionSummary.json', transactionSummary.getJson, name='jsonTransactionSummary'),
    url(r'^trans$', transactionSummary.ExpressCheckout, name='testSale'),
    url(r'^transactionSummary/CompleteOrder$',transactionSummary.CompleteOrder, name='CompleteOrder'),
    url(r'^transactionSummary/success$',transactionSummary.success, name='success'),
    url(r'^transactionSummary/failure$',transactionSummary.failure, name='failure'),

    url(r'^defaulttrans$', transactionSummary.defaultExpressCheckout, name='defaultSale'),
    url(r'^transactionSummary/defaultCompleteOrder$',transactionSummary.defaultCompleteOrder, name='defaultCompleteOrder'),
    url(r'^transactionSummary/defaultsuccess$',transactionSummary.defaultSuccess, name='defaultsuccess'),
    url(r'^transactionSummary/defaultfailure$',transactionSummary.defaultFailure, name='defaultfailure'),
)

hq_local/urls.py
from django.conf.urls import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^', include('db.urls', namespace="db")),
    #url(r'^checkout/', include('paypal_express_checkout.urls')),
    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/$', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/$', include(admin.site.urls)),
)

db/views/Basket.py
from django.core import serializers
from django.core.paginator import Paginator, EmptyPage
from django.core.urlresolvers import reverse
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.contrib import messages
from django.utils.datastructures import SortedDict
import json
from json import dumps, loads, JSONEncoder, JSONDecoder
import pickle
from db.models import Product
import unittest
import warnings
import unittest
import warnings

import urllib, md5, datetime
from cgi import parse_qs
#overide default json encoder to support non-primitive data-types
class PythonObjectEncoder(JSONEncoder):
    def default(self, obj):
        if isinstance(obj, (list, dict, str, unicode, int, float, bool, type(None))):
            return JSONEncoder.default(self, obj)
        return {'_python_object': pickle.dumps(obj)}

def as_python_object(dct):
    if '_python_object' in dct:
        return pickle.loads(str(dct['_python_object']))
    return dct

#declare products to be added to basket. It cosists of quantity of each product as well
class ProductforBasket:
    barcode = ''
    name = ''
    category = ''
    manufacturer = ''
    cost_price = None 
    quantity = None
    def __init__(self, prod_barcode, quantity, name, category, manufacturer, cost_price):
        self.barcode = prod_barcode
        self.quantity = quantity
        self.name  = name
        self.category = category
        self.manufacturer =  manufacturer
        self.cost_price = cost_price

    def as_json(self):
        # we use sorted dict to preserve order in which key/value pair is inserted
        # this is so that it won't mess up the json when we try to render it client-side
        dict = SortedDict()
        dict['barcode'] =  self.barcode
        dict['name'] = self.name
        dict['category'] = self.category
        dict['manufacturer'] = self.manufacturer
        dict['cost_price'] = "%0.2f" % self.cost_price
        dict['quantity'] = self.quantity
        return dict

#declare shopping basket for every new user using sessions
class Basket:
    productList = None
    def __init__(self):
        self.productList = []

    # API METHODS
    def AddToBasket(self, prod_barcode, quantity, name, category, manufacturer, cost_price):
        P = ProductforBasket(prod_barcode, quantity, name, category, manufacturer, cost_price)
        self.productList.append(P)
        
    def getProductList(self):
         return self.productList

    def RemoveFromBasket(self, prod_barcode):
        for i in productList:
            if( i.barcode == prod_barcode):
                productList.remove(i)

# HTTP verb: GET
# Path: /Basket
# Used for: display the user's active basker
def index(request):
    data = {}
    total = '0.0'
    try:
        total = request.session['total']
    except:
        request.session['total'] = '0.0'
        total = 0.0
    try:
        data = request.session['list']
    except:
        total = request.session['total']
    request.session['list'] = data
    request.session['total'] = total
    return render(request, 'product/AddToBasket.html', {'total': total})

#function called on adding products to basket. Adds the session variable as well.
def AddToBasket(request):
    B = Basket()
    product_l = []
    previous = []
    prevT = '0.0'
    try:
        previous = request.session['list']
    except:
        request.session['list'] = ''
    try:
        prevT = request.session['total']
    except:
        request.session['total'] = '0.0'
    total = 0
    request.session.flush()
    product_list = Product.objects.all().filter(is_valid=True)
    for product in product_list:
        temp = str(product.barcode)
        quant = temp+'Q'
        if temp in request.POST:
            quantity = request.POST[quant]
            B.AddToBasket(product.barcode, quantity, product.name, product.category, product.manufacturer, product.cost_price) 
    productList = B.getProductList()
    if productList is not None:
        for product in productList:
            total += product.cost_price * int(product.quantity)
    response_data = {}
    response_data["rows"] = [ob.as_json() for ob in productList]
    request.session['list'] = ''
    if request.session['list'] is not None:
        for product_list in previous:
            dict = SortedDict()
            dict['barcode'] =  product_list['barcode']
            dict['name'] = product_list['name']
            dict['category'] = product_list['category']
            dict['manufacturer'] =product_list['manufacturer']
            dict['cost_price'] = product_list['cost_price']
            dict['quantity'] = product_list['quantity']
            product_l.append(dict)
        for ob in productList:
            dict = ob.as_json()
            product_l.append(dict)
        nowT = float(prevT) + float(total)
        request.session['list'] = product_l
        request.session['total'] = str(nowT)
    else:
        request.session['list'] = response_data["rows"]
        request.session['total'] = str(total)
    total = request.session['total']
    return render(request, 'product/AddToBasket.html', {'total': total, 'data' : response_data})

# HTTP verb: GET
# Path: /clearBasket
# Used for: clear the contents of the basket
def clearBasket(request):
    request.session.flush()
    request.session['list'] = ''
    request.session['total'] = '0.0'
    total = request.session['total']
    return render(request, 'product/AddToBasket.html', {'total': total})

# HTTP verb: GET
# Path: along the line of /Basket.json?page=0&filter[1]=abc&column[2]=0
# Used in AJAX call from tablesorter jquery plugin from index page to sort/filter/go to next page
# return JSON data
def getJson(request):
    # url in form of : http://localhost:8000/product.json?page=0&filter[1]=a&filter[2]=b&column[8]=0
    # go through each get request variable
    product_l = []
    product = request.session['list']
    for product_list in product:
        dict = SortedDict()
        dict['barcode'] =  product_list['barcode']
        dict['name'] = product_list['name']
        dict['category'] = product_list['category']
        dict['manufacturer'] =product_list['manufacturer']
        dict['cost_price'] = product_list['cost_price']
        dict['quantity'] =product_list['quantity']
        product_l.append(dict)

    for key in request.GET: 
        if key == "filter[0]":
            product_list = product_list.filter(barcode__icontains=request.GET.get(key))
        if key == "filter[1]":
            product_list = product_list.filter(name__icontains=request.GET.get(key))
        if key == "filter[2]":
            product_list = product_list.filter(category__icontains=request.GET.get(key))
        if key == "filter[3]":
            product_list = product_list.filter(manufacturer__icontains=request.GET.get(key))
        if key == "filter[4]":
            product_list = product_list.filter(cost_price__icontains=request.GET.get(key))
        if key == "filter[5]":
            product_list = product_list.filter(quantity__icontains=request.GET.get(key))
    
    for key in request.GET:
        value = request.GET.get(key)
        if key == "column[0]":
            product_list = product_list.order_by("barcode") if value == "0" else product_list.order_by("-barcode")
        if key == "column[1]":
            product_list = product_list.order_by("name") if value == "0" else product_list.order_by("-name")
        if key == "column[2]":
            product_list = product_list.order_by("category") if value == "0" else product_list.order_by("-category")
        if key == "column[3]":
            product_list = product_list.order_by("manufacturer") if value == "0" else product_list.order_by("-manufacturer")
        if key == "column[4]":
            product_list = product_list.order_by("cost_price") if value == "0" else product_list.order_by("-cost_price")
        if key == "column[5]":
            product_list = product_list.order_by("quantity") if value == "0" else product_list.order_by("-quantity")

    paginator = Paginator(product_l, 100) #100 entries at a time
    page = request.GET.get('page') 

    try:
        product_on_page = paginator.page(int(page or 0) + 1) # if page is None, just use 0 ( and + 1 because it's zero-based on client side)
    except EmptyPage:
        product_on_page = paginator.page(paginator.num_pages)

    response_data = {}
    if len(product_l) is not None:
        length = len(product_l)
    else:
        length = 0;
    response_data["total_rows"] = length
    response_data["headers"] = ["Barcode", "Name", "Category", "Manufacturer", "Cost Price", "Quantity"]
    # serializers.serialize("json", array of obj) won't give us a json in a structure that we want.
    response_data["rows"] = product_l
    # print response_data
    return HttpResponse(json.dumps(response_data), content_type="application/json")

db/views/Testpaypal.py
from django.core import serializers
from django.core.paginator import Paginator, EmptyPage
from django.core.urlresolvers import reverse
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.contrib import messages
import json
from hq_local.settings import USER, PWD, SIGNATURE, VERSION
from db.models import Product
import unittest
import warnings
import unittest
import warnings

import urllib, md5, datetime
from cgi import parse_qs

# This class is desgined to call the Paypal API. Not used any PayPal packages to achieve this. 
# PWD, SIGNATURE  and USER is stored safely in the setting.py file to prevent access to everyone other than the admin and root
# Implemented on Sandvox enviroment. Self- declared all API functions for PayPal from the online documentation available.
# There is no direct support available for python and ExpressCheckout

class PayPal:
    """ #PayPal utility class"""
    signature_values = {}
    API_ENDPOINT = ""
    PAYPAL_URL = ""
    
    def __init__(self):
        ## Sandbox values
        self.signature_values = {
        'USER' : USER, # Edit this to your API user name
        'PWD' : PWD, # Edit this to your API password
        'SIGNATURE' : SIGNATURE, # edit this to your API signature
        'VERSION' : VERSION,
        }
        self.API_ENDPOINT = 'https://api-3t.sandbox.paypal.com/nvp' # Sandbox URL, not production
        self.PAYPAL_URL = 'https://www.sandbox.paypal.com/webscr&cmd=_express-checkout&token='
        self.signature = urllib.urlencode(self.signature_values) + "&"

    # API METHODS
    def SetExpressCheckout(self, return_url, cancel_url, product_list, **kwargs):
        params = {
            'METHOD' : "SetExpressCheckout",
            'NOSHIPPING' : 1,
            'PAYMENTACTION' : 'Sale',
            'RETURNURL' : return_url,
            'CANCELURL' : cancel_url,
            'ALLOWNOTE' :1,
            'PAYMENTREQUEST_0_PAYMENTACTION':'Sale',
            'PAYMENTREQUEST_0_CURRENCYCODE':'USD',
            'PAGESTYLE' : 'CentreOne',
        }
        m = 0;
        total = 0;
        for i in product_list:
            key = 'L_PAYMENTREQUEST_0_NAME' + str(m)
            params[key] = i['name']
            key = 'L_PAYMENTREQUEST_0_QTY' + str(m)
            params[key] = i['quantity']
            key = 'L_PAYMENTREQUEST_0_AMT' +str(m)
            params[key] = i['cost_price']
            total += (float(i['cost_price']) * int(i['quantity'])) #change by quantity
            key = 'L_PAYMENTREQUEST_0_DESC' + str(m)
            params[key] = i['manufacturer']
            key = 'L_PAYMENTREQUEST_0_NUMBER' + str(m)
            params[key] = i['barcode']
            m = m + 1
        params['PAYMENTREQUEST_0_AMT'] = total
        params.update(kwargs)
        params_string = self.signature + urllib.urlencode(params)
        response = urllib.urlopen(self.API_ENDPOINT, params_string).read()
        response_dict = parse_qs(response)
        response_token = response_dict['TOKEN'][0]
        return response_token
    
    def GetExpressCheckoutDetails(self, token, return_all = False):
        params = {
            'METHOD' : "GetExpressCheckoutDetails",
            'TOKEN' : token,
        }
        params_string = self.signature + urllib.urlencode(params)
        response = urllib.urlopen(self.API_ENDPOINT, params_string).read()
        response_dict = parse_qs(response)
        if return_all:
            return response_dict
        try:
            response_token = response_dict['TOKEN'][0]
        except KeyError:
            response_token = response_dict
        return response_token
    
    def DoExpressCheckoutPayment(self, token, payer_id, amt):
        params = {
            'METHOD' : "DoExpressCheckoutPayment",
            'TOKEN' : token,
            'AMT' : amt,
            'PAYERID' : payer_id,
            'PAYMENTACTION' : 'Sale',
        }
        params_string = self.signature + urllib.urlencode(params)
        response = urllib.urlopen(self.API_ENDPOINT, params_string).read()
        response_tokens = {}
        for token in response.split('&'):
            response_tokens[token.split("=")[0]] = token.split("=")[1]
        for key in response_tokens.keys():
                response_tokens[key] = urllib.unquote(response_tokens[key])
        print response_tokens
        return response_tokens
        
    def GetTransactionDetails(self, tx_id):
        params = {
            'METHOD' : "GetTransactionDetails", 
            'TRANSACTIONID' : tx_id,
        }
        params_string = self.signature + urllib.urlencode(params)
        response = urllib.urlopen(self.API_ENDPOINT, params_string).read()
        response_tokens = {}
        for token in response.split('&'):
            response_tokens[token.split("=")[0]] = token.split("=")[1]
        for key in response_tokens.keys():
                response_tokens[key] = urllib.unquote(response_tokens[key])
        return response_tokens    

db/views/checkpaypal.py
from django.core import serializers
from django.core.paginator import Paginator, EmptyPage
from django.core.urlresolvers import reverse
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.contrib import messages
import json

from db.models import Product
from db.views import Testpaypal
import unittest
import warnings
#import paypal
import unittest
import warnings

from Testpaypal import *
#testing paypal - not used anymore
p = PayPal()
def ExpressCheckout(barcode):
	token = p.SetExpressCheckout('120', 'http://www.yoursite.com/returnurl', 'http://www.yoursite.com/cancelurl');
	s ='https://www.sandbox.paypal.com/webscr&cmd=_express-checkout&token=' + token;

db/views/page.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.core.urlresolvers import reverse
from django.http import Http404
from hq_local.settings import *

def home(request):
    return render(request, 'home.html')
    
def management(request):
    return render(request, 'management.html')

db/templates/transactionSummary/CompleteOrder.html
{% extends "layout.html" %}
{% load staticfiles %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <h2>Order Summary</h2>
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Email</th>
                    <th>Total Amount</th>
                    <th>Currency Code</th>
                    <th>Tax Amount</th>
                    <th>Time</th>
                </tr>
            </thead>
            <tbody>
            </tbody>
            <tfoot>
                <tr>
                </tr>
                <tr>
                    <th colspan="7" class="ts-pager form-horizontal">
                    </th>
                </tr>
            </tfoot>
        </table>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
                <form role="form" action="{% url 'db:CompleteOrder' %}" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <input type="hidden" id="txtUrl" name="txtUrl"/>
            </div>
            <h4>Your order was successful. Above are the listed details</h4>
            <br />
            <br/>
            <a href="{% url 'db:indexProduct' %}" class="btn btn-primary">Continue Shopping</a><br />
    </div>
</div>
{% endblock %}

{% block javascript %}

<script src="{% static "js/jquery.tablesorter.js" %}"></script>
<script src="{% static "js/jquery.tablesorter.widgets.js" %}"></script>
<script src="{% static "js/jquery.tablesorter.pager.js" %}"></script>
<script src="{% static "js/moment.min.js" %}"></script>
<script src="{% static "js/daterangepicker.js" %}"></script>

<script>
$(function(){
    var x = document.URL;
    document.getElementById("txtUrl").value = x;

    $.extend($.tablesorter.themes.bootstrap, {
        // these classes are added to the table. To see other table classes available,
        // look here: http://twitter.github.com/bootstrap/base-css.html#tables
        table      : 'table table-bordered',
        header     : 'bootstrap-header', // give the header a gradient background
        footerRow  : '',
        footerCells: '',
        icons      : '', // add "icon-white" to make them white; this icon class is added to the <i> in the header
        sortNone   : 'bootstrap-icon-unsorted',
        sortAsc    : 'icon-chevron-up glyphicon glyphicon-chevron-up',     // includes classes for Bootstrap v2 & v3
        sortDesc   : 'icon-chevron-down glyphicon glyphicon-chevron-down', // includes classes for Bootstrap v2 & v3
        active     : '', // applied when column is sorted
        hover      : '', // use custom css here - bootstrap class may not override it
        filterRow  : '', // filter row class
        even       : '', // odd row zebra striping
        odd        : ''  // even row zebra striping
    });


    // bind to update complete event to initialize date range picker
    $("table")
    .bind("updateComplete",function(e, table) {
        if ($('#dateField').size() == 0){
            // 5th column is the date field
            $('input:eq(4)').attr("id", "dateField");
            $('#dateField').daterangepicker({
              format: 'DD/MM/YYYY'
            },
            function(start, end) {
                // simulate key-up so the filter would kick in
                $('.tablesorter-filter').keyup();
            });
        }
    });

  // Initialize tablesorter
  // ***********************

    // call the tablesorter plugin and apply the uitheme widget
    $("table").tablesorter({
        // this will apply the bootstrap theme if "uitheme" widget is included
        // the widgetOptions.uitheme is no longer required to be set
        theme : "bootstrap",

        widthFixed: true,

        headerTemplate : '{content} {icon}', // new in v2.7. Needed to add the bootstrap icon!

        // widget code contained in the jquery.tablesorter.widgets.js file
        // use the zebra stripe widget if you plan on hiding any rows (filter widget)
        widgets : [ "uitheme", "zebra", "filter"  ],

        widgetOptions : {
            // using the default zebra striping class name, so it actually isn't included in the theme variable above
            // this is ONLY needed for bootstrap theming if you are using the filter widget, because rows are hidden
            zebra : ["even", "odd"],

            // reset filters button
            filter_reset : ".reset",

            // css class name applied to the sticky header
            stickyHeaders : "tablesorter-stickyHeader"

            // set the uitheme widget to use the bootstrap theme class names
            // this is no longer required, if theme is set
            // ,uitheme : "bootstrap"
            //filter_serversideFiltering : true

        }
    })
    .tablesorterPager({

        // target the pager markup - see the HTML block below
        container: $(".ts-pager"),

        // target the pager page select dropdown - choose a page
        cssGoto  : ".pagenum",

        // remove rows from the table to speed up the sort of large tables.
        // setting this to false, only hides the non-visible rows; needed if you plan to add/remove rows with the pager enabled.
        removeRows: false,

        // output string - default is '{page}/{totalPages}';
        // possible variables: {page}, {totalPages}, {filteredPages}, {startRow}, {endRow}, {filteredRows} and {totalRows}
        output: '{startRow} - {endRow} / {filteredRows} ({totalRows})',

        ajaxUrl: '/transactionSummary.json?page={page}&{filterList:filter}&{sortList:column}',

       // ajaxUrl: 'assets/City{page}.json?{filterList:filter}&{sortList:column}',
    
        // modify the $.ajax object to allow complete control over your ajax requests
        ajaxObject: {
            dataType: 'json'
        },

        ajaxProcessing: function(data){
            if (data && data.hasOwnProperty('rows')) {
                var r, row, c, d = data.rows,
                // total number of rows (required)
                total = data.total_rows,
                // array of header names (optional)
                headers = data.headers,
                // all rows: array of arrays; each internal array has the table cell data for that row
                rows = data.rows,
                // len should match pager set size (c.size)
                len = d.length;
                // this will depend on how the json is set up - see City0.json
                // rows
                for ( r=0; r < len; r++ ) {
                    row = []; // new row array
                    // cells
                    for ( c in d[r] ) {
                        if (typeof(c) === "string") {
                            row.push(d[r][c]); // add each table cell data to row array
                        }
                    }
                    rows.push(row); // add new row array to rows array
                }
                // in version 2.10, you can optionally return $(rows) a set of table rows within a jQuery object
                return [ total, rows, headers ];
            }
        },

        size: 100,

        // css class names of pager arrows
            pager_css: {
            container   : 'tablesorter-pager',
            errorRow    : 'tablesorter-errorRow', // error information row (don't include period at beginning)
            disabled    : 'disabled'              // class added to arrows @ extremes (i.e. prev/first arrows "disabled" on first page)
        },

        // jQuery selectors
        pager_selectors: {
            container   : '.ts-pager',       // target the pager markup (wrapper)
            first       : '.first',       // go to first page arrow
            prev        : '.prev',        // previous page arrow
            next        : '.next',        // next page arrow
            last        : '.last',        // go to last page arrow
            goto        : '.gotoPage',    // go to page selector - select dropdown that sets the current page
            pageDisplay : '.pagedisplay', // location of where the "output" is displayed
            pageSize    : '.pagesize'     // page size selector - select dropdown that sets the "size" option

        }
    });

});
</script>
{% endblock %}

{% block css %}
<link href="{% static "css/tablesortertheme.css" %}" rel="stylesheet" media="screen">
<link href="{% static "css/daterangepicker-bs3.css" %}" rel="stylesheet" media="screen">
{% endblock %}

db/templates/transactionSummary/CompleteOrderDefault.html
{% extends "layout.html" %}
{% load staticfiles %}
{% block content %}
First Name: {{ details.FIRSTNAME }}<br />
Last Name: {{ details.LASTNAME }}<br />
Email: {{ details.EMAIL }}<br />
Amount: {{details.AMT}}<br/>
Currency: {{details.CURRENCYCODE}}<br/>
Extra Charges: {{details.TAXAMT}}<br/>
Time of Transaction: {{details.TIMESTAMP}}<br/>
<div class="row">
    <div class="col-md-12">
                You order was successful. Above are the listed details.
    </div>
</div>
{% endblock %}

{% block javascript %}

<script src="{% static "js/jquery.tablesorter.js" %}"></script>
<script src="{% static "js/jquery.tablesorter.widgets.js" %}"></script>
<script src="{% static "js/jquery.tablesorter.pager.js" %}"></script>

<script>
$(function(){
    var x = document.URL;
    document.getElementById("txtUrl").value = x;
});
</script>
{% endblock %}

{% block css %}
<link href="{% static "css/tablesortertheme.css" %}" rel="stylesheet" media="screen">
{% endblock %}
 No newline at end of file

db/templates/transactionSummary/failure.html
{% extends "layout.html" %}
{% load staticfiles %}
{% block content %}
<div class="row">
    <div class="col-md-12">
                Sorry your order could not be completed. Please start again.
    
    <br />
    <br />
    <a href="{% url 'db:indexProduct' %}" class="btn btn-primary">Return to Products</a><br />
    </div>
</div>
{% endblock %}

{% block javascript %}

<script src="{% static "js/jquery.tablesorter.js" %}"></script>
<script src="{% static "js/jquery.tablesorter.widgets.js" %}"></script>
<script src="{% static "js/jquery.tablesorter.pager.js" %}"></script>

<script>
$(function(){
    var x = document.URL;
    document.getElementById("txtUrl").value = x;
});
</script>
{% endblock %}

{% block css %}
<link href="{% static "css/tablesortertheme.css" %}" rel="stylesheet" media="screen">
{% endblock %}

db/templates/transactionSummary/failureDefault.html
{% extends "layout.html" %}
{% load staticfiles %}
{% block content %}
<div class="row">
    <div class="col-md-12">
                Sorry your order could not be completed. Please start again.
    </div>
</div>
{% endblock %}

{% block javascript %}

<script src="{% static "js/jquery.tablesorter.js" %}"></script>
<script src="{% static "js/jquery.tablesorter.widgets.js" %}"></script>
<script src="{% static "js/jquery.tablesorter.pager.js" %}"></script>

<script>
$(function(){
    var x = document.URL;
    document.getElementById("txtUrl").value = x;
});
</script>
{% endblock %}

{% block css %}
<link href="{% static "css/tablesortertheme.css" %}" rel="stylesheet" media="screen">
{% endblock %}
 No newline at end of file

db/templates/transactionSummary/successDefault.html
{% extends "layout.html" %}
{% load staticfiles %}
{% block content %}
First Name: {{ details.FIRSTNAME }}<br />
Last Name: {{ details.LASTNAME }}<br />
Email: {{ details.EMAIL }}<br />
Amount: {{details.AMT}}<br/>
Currency: {{details.CURRENCYCODE}}<br/>
Extra Charges: {{details.TAXAMT}}<br/>
Time of Transaction: {{details.TIMESTAMP}}<br/>
<div class="row">
    <div class="col-md-12">
                <form role="form" action="{% url 'db:defaultCompleteOrder' %}" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <input type="hidden" id="txtUrl" name="txtUrl"/>
            </div>
            <input type="submit" class="btn btn-default" value="Complete Order"></form>
    </div>
</div>
{% endblock %}

{% block javascript %}

<script src="{% static "js/jquery.tablesorter.js" %}"></script>
<script src="{% static "js/jquery.tablesorter.widgets.js" %}"></script>
<script src="{% static "js/jquery.tablesorter.pager.js" %}"></script>

<script>
$(function(){
    var x = document.URL;
    document.getElementById("txtUrl").value = x;
});
</script>
{% endblock %}

{% block css %}
<link href="{% static "css/tablesortertheme.css" %}" rel="stylesheet" media="screen">
{% endblock %}
 No newline at end of file